### ISSUE TITLE
"TypeError: Cannot read properties of undefined (reading 'ca')" 

### ISSUE THREAD

**Issue by cpwood** [small-tech/syswide-cas#1]
Many thanks for creating this fork of such a useful package!

I've noticed that it's possible to get the above exception in certain Node environments, most notably in GitHub Actions jobs.

The problem is on [line 90](https://github.com/small-tech/syswide-cas/blob/main/index.js#L90):

```js
     if (!options.ca && rootCAs.length > 0) {
```

where `options` can be undefined. Adding a `?` to this line fixes the problem:

```js
     if (!options?.ca && rootCAs.length > 0) {
```

**Comment by aral** [comment]
Hey Chris, thanks for catching this. Would you mind submitting a pull request for it? :)

**Comment by cpwood** [comment]
No worries! Done.

**Comment by aral** [comment]
Thanks! I’ll issue a patch release when I’m back at my computer :)

**Comment by ayushjain2699** [comment]
Hi,
Could you please publish the updated version of this package in npm.
Currently ` npm i @small-tech/syswide-cas` still doesn't install the corrected code

**Comment by aral** [comment]
Apologies for the delay. Version 6.0.1 is now published with Chris’s fix:

https://www.npmjs.com/package/@small-tech/syswide-cas

Also, I’ve moved the repository to Codeberg and I’m archiving the GitHub remote.
